# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Welcome to The Art of Changing... Glen Park, practitioner of Alexander Technique and Psychophysical Integration...
email: glenpark@glenpark.org.uk
description: >- # this means to ignore newlines until "baseurl:"
  Glen Park is a highly esteemed Alexander Technique and Psychophysical Integration practitioner
  and tutor based in West Sussex, UK. Glen Park provides workshops and courses
  and is the author of The Art of Changing and Touching the Soul
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.glenpark.org.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
google_tag_manager: GTM-TP6H8BZ
keywords: Glen Park, The Art of Changing, Touching the Soul, Psychophysical Integration, Alexander Technique, books, courses, CDs, workshops
author: Glen Park
# Unnsupported meta tags
# designer: Ian Forster,Graphic Alchemy
# copyright: Glen Park 2018 
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - source
   - gulpfile.js
   - gitignore
   - package.json
   - package-lock.json
   - package.lock
   - server
